### ISSUE TITLE
Please update the Wiki

### ISSUE THREAD

**Issue by Broly-Dev** [adamyeager/PushbulletSharp#21]
It is difficult to extract from the unit tests how to use the ephemerals. Please update the wiki with examples.

**Comment by adamyeager** [comment]
Sure thing! I will be working on that today.

**Comment by adamyeager** [comment]
Actually I see exactly what your issue is and why it's confusing. The Device object is missing some fields, one of which is "has_sms". You'll need to know which device has SMS in order to use that device's iden as the "TargetDeviceIden" on the SMSEphemeral object. 

I'm making an update to that object now. I'm also going to go through other objects that Pushbullet returns to make sure that the rest of the PushbulletSharp response objects have all of the properties that Pushbullet sends.

**Comment by adamyeager** [comment]
I just pushed up a hotfix on nuget which has the updated Device object with the HasSMS field. Use that device's Iden as the TargetDeviceIden for the SMSEphemeral request.

**Comment by adamyeager** [comment]
Ok, I just finished writing documentation for the ephemerals. Be sure to update to version 3.0.1 which is now available on nuget. I hope this clears things up!

https://github.com/adamyeager/PushbulletSharp/wiki/Ephemerals

**Comment by Broly-Dev** [comment]
Got it, all working. Thanks very much for your work!
