### ISSUE TITLE
Add support send to all devices

### ISSUE THREAD

**Issue by KoalaBear84** [adamyeager/PushbulletSharp#5]
In a Javascript implementation I always leave device etc empty because I just want to push it to everything. This is not possible. First I though ignoreEmptyFields was for this, but same error.

"The email property for the request is empty. This is only a problem because the device iden was empty, too."

Now I've tried with this (also tried ; as a seperator):
`string deviceIdens = PushbulletClient.CurrentUsersDevices().Devices.Select(dev => dev.iden).Aggregate((current, next) => current + "," + next);`

But then I get:

---

An exception of type 'System.ArgumentException' occurred in PushbulletSharp.dll but was not handled in user code

Additional information: Invalid JSON primitive: The.

---

And create multiple pushing is not really an option, it would clutter, they won't be completely synced for all devices. So you have to dismiss it seperately on all devices. Also it would open every push in Chrome when pushing to a Chrome 'device'.

See the following, search for 'multiple'.
https://github.com/ivkos/PushBullet-for-PHP

Thanks in advance!

**Comment by adamyeager** [comment]
Good catch. Let me look into this and see what I can do.

**Comment by adamyeager** [comment]
Sorry for the delay. It's been a while since I worked on this project and I had to bring myself back up to speed.

This feature is already supported if you provide an email address. Pushbullet's API will send the notification to all devices on the account that are active. 

If you call the `CurrentUsersInformation()` method on the PushbulletSharp client, you'll get a response that has a string property called `email` which can be passed into the request. I wrote a C# unit test to demonstrate how you can do this with the PushbulletSharp client:

```
[TestMethod]
public void PushbulletPushNoteByEmailTest()
{
    try
    {
        var currentUserInformation = Client.CurrentUsersInformation();
        Assert.IsNotNull(currentUserInformation);

        PushNoteRequest reqeust = new PushNoteRequest()
        {
            email = currentUserInformation.email,
            title = "hello world",
            body = "This is a test from my C# wrapper."
        };

        var response = Client.PushNote(reqeust);
    }
    catch (Exception ex)
    {
        Assert.Fail(ex.Message);
    }
}
```

Does this make sense?

**Comment by adamyeager** [comment]
I've also updated the Wiki on this site with this example.

https://github.com/adamyeager/PushbulletSharp/wiki/Push-Examples

**Comment by KoalaBear84** [comment]
No problem! It does make sense and it's a good workaround :P

It would be nice if it possible without the extra call, but it is indeed possible :)
